name: Mark Paulda Travel Photography
favicon: null
layout_spectrum: 0.51332
typography_spectrum: 0.17941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#312c50'
    - '#883824'
    - '#937160'
    - '#9d34c5'
    - '#97e3ee'
  brandStrength: 0.125
  lightness: 0.2179869068786502
  saturation: 0.20825225277803838
  rhythmicContrast: 0.44872372318059206
purpose: []
